### ISSUE TITLE
Adding PrimeNg to Ionic 3 (Successfull Steps)

### ISSUE THREAD

**Issue by omkarsutar** [peterennis/aeprime#1]
1. npm install primeng --save
2. npm install @angular/animations --save
3. npm install font-awesome --save
4. Add this to app.module.ts file:

import {BrowserModule} from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
imports: [
        BrowserModule,
        BrowserAnimationsModule,
        //...
    ],

5. open this file:
node_modules/@ionic/app-scripts/config/copy.config.js

6. add this code to copy.config.js file
copyPrimeng: {
src: ['{{ROOT}}/node_modules/primeng/resources/themes/omega/theme.css', '{{ROOT}}/node_modules/primeng/resources/primeng.min.css', '{{ROOT}}/node_modules/font-awesome/css/font-awesome.min.css'],
		dest: '{{BUILD}}/assets/css'
	},
	copyFontAwesome: {
		src: ["{{ROOT}}/node_modules/font-awesome/fonts/**/*"],
		dest: "{{BUILD}}/assets/fonts"
	}

7. Add these file links to index.html file:
<link rel="stylesheet" type="text/css" href="build/assets/css/theme.css" />
<link rel="stylesheet" type="text/css" href="build/assets/css/primeng.min.css" />
<link rel="stylesheet" type="text/css" href="build/assets/css/font-awesome.min.css" />

**Comment by peterennis** [comment]
@omkarsutar,

Your approach is interesting.

Typical use with Ionic is to delete node_modules when updating
and then load new files by `npm install`

Ref: https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-x/87516
Ref: https://www.techiediaries.com/upgrade-ionic-3/

You process would involve a constant update to copy.config.js
but if that works for you, then good luck.

Did you have a problem with the example not working for you?

Thanks for the comment.

**Comment by peterennis** [comment]
@omkarsutar,

I have updated to use Node 8 and npm 5.

See the README for details.
